name: hookshot_client
publish_to: none
version: 0.0.0+1

environment:
  sdk: ^3.0.6

dependencies:
  hookshot_protocol:
    path: ../protocol
  http: ^1.1.0

dev_dependencies:
  very_good_analysis: ^5.0.0+1
