services:
  postgres:
    build: postgres
    restart: unless-stopped
    ports: [5432:5432]
    volumes: [postgres:/var/lib/postgresql]
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres:
