include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: ['**.g.dart']

linter:
  rules:
    always_put_required_named_parameters_first: false
    public_member_api_docs: false
