name: hookshot_app
publish_to: none
version: 0.2.0+3

environment:
  sdk: ^3.0.6

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_web_plugins:
    sdk: flutter
  go_router: ^10.0.0
  hookshot_client:
    path: ../client
  hookshot_ui:
    path: ../ui
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  wiredash:
    git: https://github.com/millsteed/wiredash-sdk.git

dev_dependencies:
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
