name: hookshot_server
publish_to: none
version: 0.2.0+3

environment:
  sdk: ^3.0.6

dependencies:
  freezed_annotation: ^2.4.1
  hookshot_protocol:
    path: ../protocol
  json_annotation: ^4.8.1
  pointycastle: ^3.7.3
  postgres: ^2.6.2
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  shelf_hotreload: ^1.4.0
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0+1
